version: '3'
services:
  redis:
    image: redis:7.0.5-alpine
    container_name: poll-redis
    ports:
      - 6379:6379
    environment:
      ALLOW_EMPTY_PASSWORD: yes

  pg:
    image: postgres:16.1
    container_name: poll-db
    restart: always
    environment:
      - POSTGRES_DB=poll-spring-db
      - POSTGRES_USER=poll
      - POSTGRES_PASSWORD=poll
    ports:
      - 5432:5432